import { Inter } from 'next/font/google'

import { ToastContainer } from 'react-toastify'

import Navbar from '@/components/Navbar'
import MenuItem from '@/components/MenuBar'

import './globals.css'
import 'boxicons/css/boxicons.min.css'
import Footer from '@/components/Footer'
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <Navbar />
        <MenuItem />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
