export const dummyProducts = [
  {
    name: 'Organic Broccoli',
    image:
      'https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Fresh and organic broccoli, packed with nutrients.',
    price: 299,
    discount: 20,
    rating: 4.5,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['organic', 'fresh', 'healthy'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Ripe Tomatoes',
    image:
      'https://images.pexels.com/photos/1660027/pexels-photo-1660027.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Juicy and ripe tomatoes, perfect for salads or cooking.',
    price: 149,
    discount: 100,
    rating: 4.2,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['ripe', 'fresh', 'salad'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Sweet Potatoes',
    image:
      'https://images.pexels.com/photos/5505466/pexels-photo-5505466.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Nutrient-rich sweet potatoes, great for roasting or mashing.',
    price: 399,
    discount: 150,
    rating: 4.0,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['sweet', 'nutrient-rich'],
    color: 'Orange',
    stockAvailability: true,
  },
  {
    name: 'Crisp Apples',
    image:
      'https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Crisp and refreshing apples, perfect for snacking.',
    price: 199,
    discount: 50,
    rating: 4.3,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['crisp', 'refreshing', 'snack'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Fresh Spinach',
    image:
      'https://images.pexels.com/photos/2894651/pexels-photo-2894651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Tender and fresh spinach, ideal for salads or cooking.',
    price: 249,
    discount: 100,
    rating: 4.4,
    unit: 'per bunch',
    category: 'Vegetables',
    tags: ['fresh', 'tender', 'healthy'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Yellow Bell Peppers',
    image:
      'https://images.pexels.com/photos/2894651/pexels-photo-2894651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Sweet and colorful yellow bell peppers, great for cooking.',
    price: 179,
    discount: 80,
    rating: 4.1,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['sweet', 'colorful', 'cooking'],
    color: 'Yellow',
    stockAvailability: true,
  },
  {
    name: 'Bananas',
    image:
      'https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Ripe and energy-packed bananas, perfect for a quick snack.',
    price: 99,
    discount: 30,
    rating: 4.6,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['ripe', 'energy', 'snack'],
    color: 'Yellow',
    stockAvailability: true,
  },
  {
    name: 'Carrots',
    image:
      'https://images.pexels.com/photos/5505466/pexels-photo-5505466.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Crunchy and nutritious carrots, ideal for snacks or cooking.',
    price: 129,
    discount: 60,
    rating: 4.2,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['crunchy', 'nutritious', 'snack'],
    color: 'Orange',
    stockAvailability: true,
  },
  {
    name: 'Juicy Oranges',
    image:
      'https://images.pexels.com/photos/1660027/pexels-photo-1660027.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Sweet and juicy oranges, a refreshing citrus delight.',
    price: 219,
    discount: 120,
    rating: 4.3,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['sweet', 'juicy', 'refreshing'],
    color: 'Orange',
    stockAvailability: true,
  },
  {
    name: 'Cucumbers',
    image:
      'https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Cool and crisp cucumbers, perfect for salads or snacks.',
    price: 139,
    discount: 70,
    rating: 4.0,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['cool', 'crisp', 'snack'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Red Grapes',
    image:
      'https://images.pexels.com/photos/2894651/pexels-photo-2894651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Sweet and flavorful red grapes, a healthy snack option.',
    price: 349,
    discount: 180,
    rating: 4.5,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['sweet', 'flavorful', 'snack'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Avocados',
    image:
      'https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=600',
    description:
      'Creamy and nutritious avocados, perfect for salads or guacamole.',
    price: 299,
    discount: 150,
    rating: 4.4,
    unit: 'per piece',
    category: 'Vegetables',
    tags: ['creamy', 'nutritious', 'salad'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Lemons',
    image:
      'https://images.pexels.com/photos/5505466/pexels-photo-5505466.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Zesty and tangy lemons, great for cooking and beverages.',
    price: 189,
    discount: 90,
    rating: 4.2,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['zesty', 'tangy', 'cooking'],
    color: 'Yellow',
    stockAvailability: true,
  },
  {
    name: 'Red Onions',
    image:
      'https://images.pexels.com/photos/1660027/pexels-photo-1660027.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Flavorful and aromatic red onions, ideal for cooking.',
    price: 169,
    discount: 80,
    rating: 4.1,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['flavorful', 'aromatic', 'cooking'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Pineapples',
    image:
      'https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description:
      'Sweet and tropical pineapples, a delightful addition to desserts.',
    price: 499,
    discount: 20,
    rating: 4.6,
    unit: 'per piece',
    category: 'Fruits',
    tags: ['sweet', 'tropical', 'dessert'],
    color: 'Yellow',
    stockAvailability: true,
  },
  {
    name: 'Bell Peppers Mix',
    image:
      'https://images.pexels.com/photos/2894651/pexels-photo-2894651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description:
      'A mix of colorful bell peppers, perfect for stir-fries and salads.',
    price: 229,
    discount: 10,
    rating: 4.3,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['colorful', 'stir-fry', 'salad'],
    color: 'Various',
    stockAvailability: true,
  },
  {
    name: 'Strawberries',
    image:
      'https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=600',
    description:
      'Juicy and sweet strawberries, a classic favorite for snacks and desserts.',
    price: 379,
    discount: 150,
    rating: 4.5,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['juicy', 'sweet', 'snack'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Green Beans',
    image:
      'https://images.pexels.com/photos/5505466/pexels-photo-5505466.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Crunchy green beans, versatile for various cooking styles.',
    price: 209,
    discount: 120,
    rating: 4.0,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['crunchy', 'versatile', 'cooking'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Mangoes',
    image:
      'https://images.pexels.com/photos/1660027/pexels-photo-1660027.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Sweet and tropical mangoes, a delightful summer treat.',
    price: 349,
    discount: 18,
    rating: 4.4,
    unit: 'per piece',
    category: 'Fruits',
    tags: ['sweet', 'tropical', 'summer'],
    color: 'Orange',
    stockAvailability: true,
  },
  {
    name: 'Cherry Tomatoes',
    image:
      'https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Tiny and flavorful cherry tomatoes, perfect for salads.',
    price: 199,
    discount: 100,
    rating: 4.2,
    unit: 'per pint',
    category: 'Vegetables',
    tags: ['flavorful', 'salad', 'small'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Peaches',
    image:
      'https://images.pexels.com/photos/2894651/pexels-photo-2894651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Juicy and sweet peaches, a summertime delight.',
    price: 289,
    discount: 14,
    rating: 4.3,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['juicy', 'sweet', 'summer'],
    color: 'Orange',
    stockAvailability: true,
  },
  {
    name: 'Asparagus',
    image:
      'https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Tender asparagus, a versatile and healthy addition to meals.',
    price: 329,
    discount: 16,
    rating: 4.1,
    unit: 'per bunch',
    category: 'Vegetables',
    tags: ['tender', 'versatile', 'healthy'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Blueberries',
    image:
      'https://images.pexels.com/photos/5505466/pexels-photo-5505466.jpeg?auto=compress&cs=tinysrgb&w=600',
    description:
      'Sweet and antioxidant-rich blueberries, perfect for snacks or desserts.',
    price: 449,
    discount: 20,
    rating: 4.5,
    unit: 'per pint',
    category: 'Fruits',
    tags: ['sweet', 'antioxidant', 'snack'],
    color: 'Blue',
    stockAvailability: true,
  },
  {
    name: 'Zucchinis',
    image:
      'https://images.pexels.com/photos/1660027/pexels-photo-1660027.jpeg?auto=compress&cs=tinysrgb&w=600',
    description:
      'Versatile zucchinis, great for grilling, sautéing, or baking.',
    price: 179,
    discount: 90,
    rating: 4.0,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['versatile', 'grilling', 'baking'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Blackberries',
    image:
      'https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description:
      'Sweet and juicy blackberries, a flavorful addition to your diet.',
    price: 399,
    discount: 18,
    rating: 4.4,
    unit: 'per pint',
    category: 'Fruits',
    tags: ['sweet', 'juicy', 'flavorful'],
    color: 'Black',
    stockAvailability: true,
  },
  {
    name: 'Cabbage',
    image:
      'https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Fresh and crisp cabbage, perfect for salads or coleslaw.',
    price: 169,
    discount: 8,
    rating: 4.2,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['fresh', 'crisp', 'salad'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Organic Broccoli',
    image:
      'https://images.pexels.com/photos/2894651/pexels-photo-2894651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Fresh and organic broccoli, packed with nutrients.',
    price: 299,
    discount: 20,
    rating: 4.5,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['organic', 'fresh', 'healthy'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Ripe Tomatoes',
    image:
      'https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Juicy and ripe tomatoes, perfect for salads or cooking.',
    price: 149,
    discount: 10,
    rating: 4.2,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['ripe', 'fresh', 'salad'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Sweet Potatoes',
    image:
      'https://images.pexels.com/photos/5505466/pexels-photo-5505466.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Nutrient-rich sweet potatoes, great for roasting or mashing.',
    price: 399,
    discount: 15,
    rating: 4.0,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['sweet', 'nutrient-rich'],
    color: 'Orange',
    stockAvailability: true,
  },
  {
    name: 'Crisp Apples',
    image:
      'https://images.pexels.com/photos/5505466/pexels-photo-5505466.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Crisp and refreshing apples, perfect for snacking.',
    price: 199,
    discount: 50,
    rating: 4.3,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['crisp', 'refreshing', 'snack'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Fresh Spinach',
    image:
      'https://images.pexels.com/photos/1660027/pexels-photo-1660027.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Leafy and nutritious spinach, ideal for salads or cooking.',
    price: 249,
    discount: 12,
    rating: 4.4,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['fresh', 'nutritious', 'leafy'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Bananas',
    image:
      'https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Sweet and energizing bananas, a quick and healthy snack.',
    price: 99,
    discount: 8,
    rating: 4.1,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['sweet', 'energizing', 'snack'],
    color: 'Yellow',
    stockAvailability: true,
  },
  {
    name: 'Carrots',
    image:
      'https://images.pexels.com/photos/2894651/pexels-photo-2894651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description:
      'Crunchy and vibrant carrots, perfect for snacking or cooking.',
    price: 179,
    discount: 90,
    rating: 4.2,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['crunchy', 'vibrant', 'snack'],
    color: 'Orange',
    stockAvailability: true,
  },
  {
    name: 'Gala Apples',
    image:
      'https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Sweet and flavorful Gala apples, great for desserts.',
    price: 229,
    discount: 10,
    rating: 4.3,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['sweet', 'flavorful', 'dessert'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Avocados',
    image:
      'https://images.pexels.com/photos/1660027/pexels-photo-1660027.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Creamy and nutritious avocados, perfect for guacamole.',
    price: 349,
    discount: 150,
    rating: 4.5,
    unit: 'per piece',
    category: 'Fruits',
    tags: ['creamy', 'nutritious', 'guacamole'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Cucumbers',
    image:
      'https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Cool and refreshing cucumbers, great for salads.',
    price: 129,
    discount: 70,
    rating: 4.0,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['cool', 'refreshing', 'salad'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Oranges',
    image:
      'https://images.pexels.com/photos/2894651/pexels-photo-2894651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Juicy and vitamin-packed oranges, a healthy citrus snack.',
    price: 219,
    discount: 100,
    rating: 4.2,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['juicy', 'vitamin-packed', 'citrus'],
    color: 'Orange',
    stockAvailability: true,
  },
  {
    name: 'Bell Peppers',
    image:
      'https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Colorful bell peppers, great for cooking or snacking.',
    price: 299,
    discount: 120,
    rating: 4.4,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['colorful', 'cooking', 'snack'],
    color: 'Various',
    stockAvailability: true,
  },
  {
    name: 'Pineapples',
    image:
      'https://images.pexels.com/photos/5505466/pexels-photo-5505466.jpeg?auto=compress&cs=tinysrgb&w=600',
    description:
      'Sweet and tropical pineapples, perfect for desserts or smoothies.',
    price: 499,
    discount: 20,
    rating: 4.6,
    unit: 'per piece',
    category: 'Fruits',
    tags: ['sweet', 'tropical', 'dessert'],
    color: 'Yellow',
    stockAvailability: true,
  },
  {
    name: 'Organic Broccoli',
    image:
      'https://images.pexels.com/photos/1660027/pexels-photo-1660027.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Fresh and organic broccoli, packed with nutrients.',
    price: 299,
    discount: 20,
    rating: 4.5,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['organic', 'fresh', 'healthy'],
    color: 'Green',
    stockAvailability: true,
  },
  {
    name: 'Ripe Tomatoes',
    image:
      'https://images.pexels.com/photos/1414651/pexels-photo-1414651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Juicy and ripe tomatoes, perfect for salads or cooking.',
    price: 149,
    discount: 100,
    rating: 4.2,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['ripe', 'fresh', 'salad'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Sweet Potatoes',
    image:
      'https://images.pexels.com/photos/2894651/pexels-photo-2894651.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Nutrient-rich sweet potatoes, great for roasting or mashing.',
    price: 399,
    discount: 15,
    rating: 4.0,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['sweet', 'nutrient-rich'],
    color: 'Orange',
    stockAvailability: true,
  },
  {
    name: 'Crisp Apples',
    image:
      'https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Crisp and refreshing apples, perfect for snacking.',
    price: 199,
    discount: 50,
    rating: 4.3,
    unit: 'per pound',
    category: 'Fruits',
    tags: ['crisp', 'refreshing', 'snack'],
    color: 'Red',
    stockAvailability: true,
  },
  {
    name: 'Fresh Carrots',
    image:
      'https://images.pexels.com/photos/5505466/pexels-photo-5505466.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Crunchy and fresh carrots, ideal for salads or snacks.',
    price: 129,
    discount: 80,
    rating: 4.1,
    unit: 'per pound',
    category: 'Vegetables',
    tags: ['fresh', 'crunchy', 'snack'],
    color: 'Orange',
    stockAvailability: true,
  },
]
